#
# Copyright (C) 2025 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

set(TARGET_NAME launcher)

# ######################################################################################################################
# Sources
# ######################################################################################################################

set(SOURCES instanceidprovider.cpp runtimes.cpp)

# ######################################################################################################################
# Libraries
# ######################################################################################################################

set(LIBRARIES Poco::JSON aos::core::common::tools aos::sm::utils)

if(WITH_RUNTIME_CONTAINER)
    list(APPEND LIBRARIES aos::sm::runtimes::container)
endif()

if(WITH_RUNTIME_BOOT)
    list(APPEND LIBRARIES aos::sm::runtimes::boot)
endif()

if(WITH_RUNTIME_ROOTFS)
    list(APPEND LIBRARIES aos::sm::runtimes::rootfs)
endif()

# ######################################################################################################################
# Target
# ######################################################################################################################

add_module(
    TARGET_NAME
    ${TARGET_NAME}
    LOG_MODULE
    STACK_USAGE
    ${AOS_STACK_USAGE}
    SOURCES
    ${SOURCES}
    LIBRARIES
    ${LIBRARIES}
)

# ######################################################################################################################
# Tests
# ######################################################################################################################

if(WITH_TEST)
    add_subdirectory(tests)
endif()

# ######################################################################################################################
# Runtimes
# ######################################################################################################################

add_subdirectory(runtimes)
